/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-11-16 18:55:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class painel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <!--  meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"-->\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("\n");
      out.write("    <title>Health Track 1.4 - Dashbord</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core CSS -->\n");
      out.write("    <link href=\"resources/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"resources/css/stylish-portfolio.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom Fonts -->\n");
      out.write("    <link href=\"resources/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    <link rel=\"shortcut icon\" href=\"resoruce/img/logo.png\" type=\"image/x-icon\" />\n");
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("        <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Menu -->\n");
      out.write("    <a id=\"menu-toggle\" href=\"#\" class=\"btn btn-dark btn-lg toggle\" style=\"padding-top: 10px; padding-bottom: 10px;\"><i class=\"fa fa-bars\"></i></a>\n");
      out.write("    <nav id=\"sidebar-wrapper\">\n");
      out.write("        <ul class=\"sidebar-nav\">\n");
      out.write("            <a id=\"menu-close\" href=\"#\" class=\"btn btn btn-lg pull-right toggle\"><i class=\"fa fa-times\" ></i></a>\n");
      out.write("            <li class=\"sidebar-brand\">\n");
      out.write("                <a href=\"#painel\" onclick=$(\"#menu-close\").click();>Home</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#cadastrar\" onclick=$(\"#menu-close\").click();>Cadastrar Alimentos</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#atividade\" onclick=$(\"#menu-close\").click();>Cadastrar atividades</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#portfolio\" onclick=$(\"#menu-close\").click();>Informaações Pessoais</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#portfolio\" onclick=$(\"#menu-close\").click();>Personalizar Treino e Alimento</a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"#iniciaratividade\" onclick=$(\"#menu-close\").click();><b><font color=\"#90EE90\">Iniciar atividade</font></b></a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"index.jsp#\"><b><font color=\"#FF3030\">SAIR</font></b></a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("        </ul>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <!-- Header -->\n");
      out.write("    <header id= \"painel\" class=\"header\">\n");
      out.write("        <div class=\"toggle\">\n");
      out.write("            <h1>Bem Vindo</h1> \n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div id=\"graficos\" class=\"col-md-2 col-md-offset-1\">\n");
      out.write("                    <img src=\"resoruce/img/calorias.jpg\">         \n");
      out.write("                </div>\n");
      out.write("                <div id=\"graficos\" class=\"col-md-3 col-md-offset-4\">\n");
      out.write("                    <img src=\"resoruce/img/peso.jpg\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div id=\"graficos\" class=\"col-md-2 col-md-offset-1\">\n");
      out.write("                    <img src=\"resoruce/img/kcal.jpg\">         \n");
      out.write("                </div>\n");
      out.write("                <div id=\"graficos\" class=\"col-md-3 col-md-offset-4\">\n");
      out.write("                    <img src=\"resoruce/img/metas.jpg\">\n");
      out.write("                </div>\n");
      out.write("            </div>        \n");
      out.write("            <br>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <!-- Cadastrar Alimentos -->\n");
      out.write("    <section id=\"cadastrar\" class=\"header\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row text-center\">\n");
      out.write("                <div class=\"col-md-10 col-md-offset-1\">\n");
      out.write("                    <h2><b><font color=\"#FFFFFF\">Cadastrar Alimentos</font></b></h2>\n");
      out.write("                    <hr class=\"small\">\n");
      out.write("                    <h3><font color=\"#FFFFFF\">Kcal Diarias</font></h3>\n");
      out.write("                   <div class=\"progress\">\n");
      out.write("                      <div class=\"progress-bar progress-bar-striped active\" role=\"progressbar\" aria-valuenow=\"45\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 45%\">\n");
      out.write("                        <span class=\"sr-only\">45% Complete</span>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-4\">\n");
      out.write("                        <h4><font color=\"#FFFFFF\"><b>Carboidratos 10g</b></font></h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4\">\n");
      out.write("                        <h4><font color=\"#FFFFFF\"><b>Proteinas 10g</b></font></h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4\">\n");
      out.write("                        <h4><font color=\"#FFFFFF\"><b>Gorduras 10g</b></font></h4>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                    <div class=\"row\" style=\"padding-top: 100px;\">\n");
      out.write("                        <div class=\" col-md-4\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-light\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@mdo\">Café da Manhâ</button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\" col-md-4\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-light\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@mdo\">Lanche da Manhâ</button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\" col-md-4\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-light\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@mdo\">Almoço</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\" style=\"padding-top: 200px;\">\n");
      out.write("                        <div class=\" col-md-4\">\n");
      out.write("                                <button type=\"button\" class=\"btn btn-light\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@mdo\">Lanche da Tarde</button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\" col-md-4\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-light\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@mdo\">Jantar</button>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\" col-md-4\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-light\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@mdo\">Ceia</button>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <!-- /.row (nested) -->\n");
      out.write("                </div>\n");
      out.write("                <!-- /.col-lg-10 -->\n");
      out.write("                <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\">\n");
      out.write("                  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("                    <div class=\"modal-content\">\n");
      out.write("                      <div class=\"modal-header\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\n");
      out.write("                        <h4 class=\"modal-title\" id=\"exampleModalLabel\">Digite seus alimentos</h4>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"modal-body\">\n");
      out.write("                        <form>\n");
      out.write("                          <div class=\"form-group\">\n");
      out.write("                            <label for=\"recipient-name\" class=\"control-label\">Liquidos:</label>\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"recipient-name\">\n");
      out.write("                          </div>\n");
      out.write("                          <div class=\"form-group\">\n");
      out.write("                            <label for=\"message-text\" class=\"control-label\">Solidos:</label>\n");
      out.write("                            <textarea class=\"form-control\" id=\"message-text\"></textarea>\n");
      out.write("                          </div>\n");
      out.write("                        </form>\n");
      out.write("                      </div>\n");
      out.write("                      <div class=\"modal-footer\">\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Fechar</button>\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary\">Adicionar</button>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- /.row -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.container -->\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Cadastrar Atividades -->\n");
      out.write("    <aside id=\"atividade\" class=\"callout\">\n");
      out.write("                <div  id=\"catividades\"  class=\"container\">\n");
      out.write("                 <form class=\"form-horizontal\">\n");
      out.write("                      <div class=\"form-group form-group-md\" style=\"padding-right: 30px;\">\n");
      out.write("                        <div class=\"col-md-offset-5 col-md-4 \">\n");
      out.write("                          <input class=\"form-control\" type=\"text\" id=\"formGroupInputLarge\" placeholder=\"Data de hoje\" style=\"width: 200px;\">\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </form>\n");
      out.write("            <div class=\"row text-center\">\n");
      out.write("                <div class=\"col-md-10 col-md-offset-1\">\n");
      out.write("                    <h2><b><font color=\"#FFFFFF\">Cadastrar Atividades</font></b></h2>\n");
      out.write("                    <hr class=\"small\">\n");
      out.write("                    <h3><font color=\"#FFFFFF\">Meta de Kcal Diaria</font></h3>\n");
      out.write("                   <div class=\"progress\">\n");
      out.write("                      <div class=\"progress-bar progress-bar-striped active\" role=\"progressbar\" aria-valuenow=\"45\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 20%\" >\n");
      out.write("                        <span class=\"sr-only\">20% Complete</span>\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("        </div>\n");
      out.write("            <div class=\"btn-group\">\n");
      out.write("              <button type=\"button\" class=\"btn btn-warning\">Atividade Fisica</button>\n");
      out.write("              <button type=\"button\" class=\"btn btn-warning dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
      out.write("                <span class=\"caret\"></span>\n");
      out.write("                <span class=\"sr-only\">Toggle Dropdown</span>\n");
      out.write("              </button>\n");
      out.write("              <ul class=\"dropdown-menu\">\n");
      out.write("                <li><a href=\"#\">Caminhada</a></li>\n");
      out.write("                <li><a href=\"#\">Treino em academia</a></li>\n");
      out.write("                <li><a href=\"#\">Corrida</a></li>\n");
      out.write("                <li><a href=\"#\">Bicicleta</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>        \n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-offset-5 col-md-2\">\n");
      out.write("                <div class=\"input-group\">\n");
      out.write("                  <span class=\"input-group-addon\">\n");
      out.write("                    <input type=\"checkbox\" aria-label=\"...\">\n");
      out.write("                  </span>\n");
      out.write("                  <input type=\"text\" class=\"form-control\" aria-label=\"...\" placeholder=\"Nome da atividade\">\n");
      out.write("                </div><!-- /input-group -->\n");
      out.write("              </div><!-- /.col-lg-6 -->            \n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-offset-5 col-md-2\">\n");
      out.write("                <div class=\"input-group\">\n");
      out.write("                  <span class=\"input-group-addon\">\n");
      out.write("                    <input type=\"checkbox\" aria-label=\"...\">\n");
      out.write("                  </span>\n");
      out.write("                  <input type=\"text\" class=\"form-control\" aria-label=\"...\" placeholder=\"Tempo de atividade(em min)\">\n");
      out.write("                </div><!-- /input-group -->\n");
      out.write("              </div><!-- /.col-lg-6 -->            \n");
      out.write("            </div>  \n");
      out.write("            <div class=\"row\">\n");
      out.write("              <div class=\"col-md-offset-5 col-md-2\">\n");
      out.write("                <div class=\"input-group\" style=\"padding-bottom: 20px\">\n");
      out.write("                  <span class=\"input-group-addon\">\n");
      out.write("                    <input type=\"checkbox\" aria-label=\"...\">\n");
      out.write("                  </span>\n");
      out.write("                  <input type=\"text\" class=\"form-control\" aria-label=\"...\" placeholder=\"Calorias\">\n");
      out.write("                </div><!-- /input-group -->\n");
      out.write("              </div><!-- /.col-lg-6 -->            \n");
      out.write("            </div> \n");
      out.write("                <button type=\"button\" class=\"btn btn-success\" padding-top><B>ADICIONAR</B></button>\n");
      out.write("\n");
      out.write("    </aside>\n");
      out.write("\n");
      out.write("    <!-- Smart Personal -->\n");
      out.write("    <section id=\"portfolio\" class=\"portfolio\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\" style=\"padding-top: 250px;\">\n");
      out.write("                <div class=\"col-md-10 col-md-offset-1 text-center\">\n");
      out.write("                    <h2><b>Treino Personalizado</b></h2>\n");
      out.write("                    <hr class=\"small\">\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\".bs-example-modal-lg\">Criar Planilha Alimentar Pesonalizada</button>\n");
      out.write("\n");
      out.write("                        <div class=\"modal fade bs-example-modal-lg\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\">\n");
      out.write("                          <div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("                            <div class=\"modal-content\">\n");
      out.write("                              <h2><font color=\"#1C1C1C\">\n");
      out.write("                              Café da manha\n");
      out.write("                              </font></h2>\n");
      out.write("                              <h3><font color=\"#1C1C1C\">\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              </font></h3>\n");
      out.write("                              <h2><font color=\"#1C1C1C\">\n");
      out.write("                              Lanche da manha\n");
      out.write("                              </font></h2>\n");
      out.write("                              <h3><font color=\"#1C1C1C\">\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              </font></h3>\n");
      out.write("                              <h2><font color=\"#1C1C1C\">\n");
      out.write("                              Almoço\n");
      out.write("                              </font></h2>\n");
      out.write("                              <h3><font color=\"#1C1C1C\">\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              </font></h3>\n");
      out.write("                              <h2><font color=\"#1C1C1C\">\n");
      out.write("                              Lanche da Tarde\n");
      out.write("                              </font></h2>\n");
      out.write("                              <h3><font color=\"#1C1C1C\">\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              </font></h3>\n");
      out.write("                              <h2><font color=\"#1C1C1C\">\n");
      out.write("                              Jantar\n");
      out.write("                              </font></h2>\n");
      out.write("                              <h3><font color=\"#1C1C1C\">\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              </font></h3>\n");
      out.write("                              <h2><font color=\"#1C1C1C\">\n");
      out.write("                              Ceia\n");
      out.write("                              </font></h2>\n");
      out.write("                              <h3><font color=\"#1C1C1C\">\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              </font></h3>\n");
      out.write("                            </div>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>          \n");
      out.write("            </div>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-md-10 col-md-offset-1 text-center\" style=\"padding-top: 250px;\">\n");
      out.write("                    <button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\".bs-example-modal-sm\">Criar Planinha de Treinos</button>\n");
      out.write("\n");
      out.write("                    <div class=\"modal fade bs-example-modal-sm\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"mySmallModalLabel\">\n");
      out.write("                      <div class=\"modal-dialog modal-sm\" role=\"document\">\n");
      out.write("                        <div class=\"modal-content\">\n");
      out.write("                          <h2><font color=\"#1C1C1C\">\n");
      out.write("                              Treinamento <b><font color=\"#FF0000\">A</font></b>\n");
      out.write("                              </font></h2>\n");
      out.write("                              <h3><font color=\"#1C1C1C\">\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              </font></h3>\n");
      out.write("                              <h2><font color=\"#1C1C1C\">\n");
      out.write("                              Treinamento <b><font color=\"#FF0000\">B</font></b>\n");
      out.write("                              </font></h2>\n");
      out.write("                              <h3><font color=\"#1C1C1C\">\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              </font></h3>\n");
      out.write("                              <h2><font color=\"#1C1C1C\">\n");
      out.write("                              Treinamento <b><font color=\"#FF0000\">C</font></b>\n");
      out.write("                              </font></h2>\n");
      out.write("                              <h3><font color=\"#1C1C1C\">\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              -</br>\n");
      out.write("                              </font></h3>\n");
      out.write("                        </div>\n");
      out.write("                      </div>\n");
      out.write("                    </div> \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </section>\n");
      out.write("    <!-- Iniciar Atividade -->\n");
      out.write("    <section id=\"iniciaratividade\" class=\"itstime\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-offset-4 col-md-4 text-center\">\n");
      out.write("              <h1><font><b>Comece a se exercitar!!</b></font></h1>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("                          <div class=\"\">\n");
      out.write("              <div id=\"carousel-example-generic\" class=\"carousel slide\" data-ride=\"carousel\" style=\"padding-left: 330px; background-color: #FFFFFF;\">\n");
      out.write("                <!-- Indicators -->\n");
      out.write("                <ol class=\"carousel-indicators\">\n");
      out.write("                  <li data-target=\"#carousel-example-generic\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("                  <li data-target=\"#carousel-example-generic\" data-slide-to=\"1\"></li>\n");
      out.write("                  <li data-target=\"#carousel-example-generic\" data-slide-to=\"2\"></li>\n");
      out.write("                </ol>\n");
      out.write("\n");
      out.write("                <!-- Wrapper for slides -->\n");
      out.write("                <div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("                  <div class=\"item active\">\n");
      out.write("                    <a href=\"#\"><img src=\"resoruce/img/treino.jpg\" alt=\"\" style=\"padding-top: 20px;padding-left: 250px; width \"></a>\n");
      out.write("                    <div class=\"carousel-caption\">\n");
      out.write("                      <h2 style=\"padding-right:300px;\">Treino</h2>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"item\">\n");
      out.write("                    <a href=\"#\"><img src=\"resoruce/img/peito.png\" alt=\"\" style=\" padding-top:20px; padding-left: 250px; width: 620px; height: 465px;\"></a>\n");
      out.write("                    <div class=\"carousel-caption\">\n");
      out.write("                      <h2 style=\"padding-right:300px;\">Treino de Peito</h2>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"item\">\n");
      out.write("                    <a href=\"#\"><img src=\"resoruce/img/perna.jpg\" alt=\"\" style=\" padding-left: 250px; padding-top: 20px;  width width: 620px; height: 465px;\"></a>\n");
      out.write("                    <div class=\"carousel-caption\">\n");
      out.write("                      <h2 style=\"padding-right:300px;\">Treino de Perna</h2>\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                  ...\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <!-- Controls -->\n");
      out.write("                <a class=\"left carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"prev\">\n");
      out.write("                  <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\n");
      out.write("                  <span class=\"sr-only\">Previous</span>\n");
      out.write("                </a>\n");
      out.write("                <a class=\"right carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"next\">\n");
      out.write("                  <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\n");
      out.write("                  <span class=\"sr-only\">Next</span>\n");
      out.write("                </a>\n");
      out.write("              </div>              \n");
      out.write("                          </div>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write(" \n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Footer -->\n");
      out.write("    <footer>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-lg-10 col-lg-offset-1 text-center\">\n");
      out.write("                    <h4><strong>Health Track</strong>\n");
      out.write("                    </h4>\n");
      out.write("                    <br>\n");
      out.write("                    <ul class=\"list-inline\">\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-facebook fa-fw fa-3x\"></i></a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-twitter fa-fw fa-3x\"></i></a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-dribbble fa-fw fa-3x\"></i></a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                    <hr class=\"small\">\n");
      out.write("                    <p class=\"text-muted\">Copyright &copy; Health Track 2017</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <a id=\"to-top\" href=\"#top\" class=\"btn btn-dark btn-lg\"><i class=\"fa fa-chevron-up fa-fw fa-1x\"></i></a>\n");
      out.write("    </footer>\n");
      out.write("\n");
      out.write("    <!-- jQuery -->\n");
      out.write("    <script src=\"resoruce/js/jquery.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap Core JavaScript -->\n");
      out.write("    <script src=\"resoruce/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- Custom Theme JavaScript -->\n");
      out.write("    <script>\n");
      out.write("    // Closes the sidebar menu\n");
      out.write("    $(\"#menu-close\").click(function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        $(\"#sidebar-wrapper\").toggleClass(\"active\");\n");
      out.write("    });\n");
      out.write("    // Opens the sidebar menu\n");
      out.write("    $(\"#menu-toggle\").click(function(e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        $(\"#sidebar-wrapper\").toggleClass(\"active\");\n");
      out.write("    });\n");
      out.write("    // Scrolls to the selected menu item on the page\n");
      out.write("    $(function() {\n");
      out.write("        $('a[href*=#]:not([href=#],[data-toggle],[data-target],[data-slide])').click(function() {\n");
      out.write("            if (location.pathname.replace(/^\\//, '') == this.pathname.replace(/^\\//, '') || location.hostname == this.hostname) {\n");
      out.write("                var target = $(this.hash);\n");
      out.write("                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');\n");
      out.write("                if (target.length) {\n");
      out.write("                    $('html,body').animate({\n");
      out.write("                        scrollTop: target.offset().top\n");
      out.write("                    }, 1000);\n");
      out.write("                    return false;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("    //#to-top button appears after scrolling\n");
      out.write("    var fixed = false;\n");
      out.write("    $(document).scroll(function() {\n");
      out.write("        if ($(this).scrollTop() > 250) {\n");
      out.write("            if (!fixed) {\n");
      out.write("                fixed = true;\n");
      out.write("                // $('#to-top').css({position:'fixed', display:'block'});\n");
      out.write("                $('#to-top').show(\"slow\", function() {\n");
      out.write("                    $('#to-top').css({\n");
      out.write("                        position: 'fixed',\n");
      out.write("                        display: 'block'\n");
      out.write("                    });\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("        } else {\n");
      out.write("            if (fixed) {\n");
      out.write("                fixed = false;\n");
      out.write("                $('#to-top').hide(\"slow\", function() {\n");
      out.write("                    $('#to-top').css({\n");
      out.write("                        display: 'none'\n");
      out.write("                    });\n");
      out.write("                });\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    // Disable Google Maps scrolling\n");
      out.write("    // See http://stackoverflow.com/a/25904582/1607849\n");
      out.write("    // Disable scroll zooming and bind back the click event\n");
      out.write("    var onMapMouseleaveHandler = function(event) {\n");
      out.write("        var that = $(this);\n");
      out.write("        that.on('click', onMapClickHandler);\n");
      out.write("        that.off('mouseleave', onMapMouseleaveHandler);\n");
      out.write("        that.find('iframe').css(\"pointer-events\", \"none\");\n");
      out.write("    }\n");
      out.write("    var onMapClickHandler = function(event) {\n");
      out.write("            var that = $(this);\n");
      out.write("            // Disable the click handler until the user leaves the map area\n");
      out.write("            that.off('click', onMapClickHandler);\n");
      out.write("            // Enable scrolling zoom\n");
      out.write("            that.find('iframe').css(\"pointer-events\", \"auto\");\n");
      out.write("            // Handle the mouse leave event\n");
      out.write("            that.on('mouseleave', onMapMouseleaveHandler);\n");
      out.write("        }\n");
      out.write("        // Enable map zooming with mouse scroll when the user clicks the map\n");
      out.write("    $('.map').on('click', onMapClickHandler);\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
